use anyhow::{Context, Result, bail};
use askama::Template;
use axum::extract::{DefaultBodyLimit, Multipart};
use axum::http::{HeaderMap, HeaderValue, StatusCode, header};
use axum::response::{Html, IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use clap::{Parser, Subcommand, ValueEnum};
use image::ImageFormat;
use serde_json::json;
use std::io::Cursor;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use stitcher::{
    EvalThresholds, PanMode, SourceMap, SourceSelection, StitchOptions, StitchReport,
    detect_duplicates, draw_duplicate_overlay, draw_evaluation_overlay, draw_source_block_overlay,
    evaluate_stitch, generate_source_map, load_images, stitch_images,
    stitch_images_with_source_map,
};
use tokio::fs;
use tower_http::services::ServeDir;
use tracing_subscriber::EnvFilter;
use uuid::Uuid;

#[derive(Parser, Debug)]
#[command(name = "stitcher")]
#[command(about = "Reconstruct a single still from ordered pan screenshots")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Stitch images from the command line.
    Stitch(StitchArgs),
    /// Run the browser-based GUI.
    Serve(ServeArgs),
    /// Evaluate a stitched image using a stitch report/source map and write quality metrics/overlays.
    Eval(EvalArgs),
}

#[derive(Parser, Debug)]
struct StitchArgs {
    /// Ordered input screenshots, earliest to latest.
    #[arg(required = true)]
    inputs: Vec<PathBuf>,

    /// Output PNG/JPEG path.
    #[arg(short, long)]
    output: PathBuf,

    /// Run duplicate-region success gate.
    #[arg(long)]
    check_duplicates: bool,

    /// Write duplicate overlay PNG next to the output.
    #[arg(long)]
    duplicate_overlay: bool,

    /// Pan detection mode.
    #[arg(long, value_enum, default_value_t = CliPanMode::Auto)]
    mode: CliPanMode,

    /// Source selection method for overlaps.
    #[arg(long, value_enum, default_value_t = CliSourceSelection::NearestCenter)]
    source_selection: CliSourceSelection,

    #[arg(long, default_value_t = 30)]
    min_shift_y: i32,
    #[arg(long)]
    max_shift_y: Option<i32>,
    #[arg(long, default_value_t = 30)]
    min_shift_x: i32,
    #[arg(long)]
    max_shift_x: Option<i32>,
    #[arg(long, default_value_t = 60)]
    max_drift_x: i32,
    #[arg(long, default_value_t = 60)]
    max_drift_y: i32,
    #[arg(long, default_value_t = 4)]
    align_scale: usize,
    #[arg(long, default_value_t = 3)]
    snap_x: i32,

    /// Use the longest monotonic frame subsequence for overlap seams; excluded frames only fill unique holes.
    #[arg(long)]
    monotonic_frame_filter: bool,

    /// Motion-aware seam penalty weight for --source-selection seam-dp-motion.
    #[arg(long, default_value_t = 2.0)]
    seam_motion_weight: f32,

    /// Radius for local temporal-difference seam penalty.
    #[arg(long, default_value_t = 6)]
    seam_motion_radius: u32,

    /// Ignore local temporal differences below this threshold.
    #[arg(long, default_value_t = 12.0)]
    seam_motion_threshold: f32,

    /// Dilate detected moving-foreground seam mask by this many pixels. Set to 0 to disable.
    #[arg(long, default_value_t = 0)]
    seam_motion_mask_dilate: u32,

    /// Hard seam penalty inside the dilated moving-foreground mask. Set to 0 to disable.
    #[arg(long, default_value_t = 0.0)]
    seam_motion_hard_penalty: f32,

    /// Weight for avoiding strong luminance edges in seam search.
    #[arg(long, default_value_t = 0.15)]
    seam_edge_weight: f32,

    /// Save a JSON report with shifts, canvas positions, and duplicate findings.
    #[arg(long)]
    report: Option<PathBuf>,

    /// Save a grayscale PNG source map: 0 = uncovered, otherwise source index + 1.
    #[arg(long)]
    source_map: Option<PathBuf>,
}

#[derive(Parser, Debug)]
struct EvalArgs {
    /// Stitched image to evaluate.
    #[arg(long)]
    stitched: PathBuf,

    /// Stitch report JSON generated by `stitcher stitch --report`.
    #[arg(long)]
    report: PathBuf,

    /// Ordered input screenshots used for the stitch. Required if --source-map is omitted.
    #[arg(long)]
    inputs: Vec<PathBuf>,

    /// Optional source-map PNG generated by `stitcher stitch --source-map`.
    #[arg(long)]
    source_map: Option<PathBuf>,

    /// Write evaluation JSON report.
    #[arg(long)]
    output: PathBuf,

    /// Write yellow/red artifact overlay.
    #[arg(long)]
    overlay: Option<PathBuf>,

    /// Write tinted source-block overlay.
    #[arg(long)]
    source_block_overlay: Option<PathBuf>,

    /// Write crops around the largest high-risk seam components for inspection.
    #[arg(long)]
    component_crops_dir: Option<PathBuf>,

    /// Padding around each high-risk component crop.
    #[arg(long, default_value_t = 40)]
    component_crop_padding: u32,

    /// Maximum number of high-risk component crops to write.
    #[arg(long, default_value_t = 12)]
    max_component_crops: usize,

    #[arg(long, default_value_t = 250)]
    max_high_risk_boundary_pixels: u32,

    #[arg(long, default_value_t = 300)]
    max_largest_risky_component_area: u32,

    /// Minimum average edge/sharpness score. Set to 0 to disable.
    #[arg(long, default_value_t = 0.0)]
    min_mean_gradient: f32,

    /// Minimum 95th percentile edge/sharpness score. Set to 0 to disable.
    #[arg(long, default_value_t = 0.0)]
    min_p95_gradient: f32,

    /// Allow the stitched image to be smaller than the reported full canvas.
    #[arg(long)]
    allow_crop: bool,
}

#[derive(Parser, Debug)]
struct ServeArgs {
    /// Address to bind, e.g. 127.0.0.1:3000.
    #[arg(long, default_value = "127.0.0.1:3000")]
    bind: SocketAddr,

    /// Directory for generated web outputs.
    #[arg(long, default_value = "./stitcher-web-output")]
    output_dir: PathBuf,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum CliPanMode {
    Auto,
    Vertical,
    Horizontal,
}

impl From<CliPanMode> for PanMode {
    fn from(value: CliPanMode) -> Self {
        match value {
            CliPanMode::Auto => PanMode::Auto,
            CliPanMode::Vertical => PanMode::Vertical,
            CliPanMode::Horizontal => PanMode::Horizontal,
        }
    }
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum CliSourceSelection {
    NearestCenter,
    SeamDp,
    SeamDpMotion,
}

impl From<CliSourceSelection> for SourceSelection {
    fn from(value: CliSourceSelection) -> Self {
        match value {
            CliSourceSelection::NearestCenter => SourceSelection::NearestCenter,
            CliSourceSelection::SeamDp => SourceSelection::SeamDp,
            CliSourceSelection::SeamDpMotion => SourceSelection::SeamDpMotion,
        }
    }
}

#[derive(Template)]
#[template(path = "index.html")]
struct IndexTemplate;

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::Stitch(args) => stitch_cli(args),
        Commands::Serve(args) => serve(args).await,
        Commands::Eval(args) => eval_cli(args),
    }
}

fn options_from_args(args: &StitchArgs) -> StitchOptions {
    StitchOptions {
        mode: args.mode.into(),
        source_selection: args.source_selection.into(),
        min_shift_y: args.min_shift_y,
        max_shift_y: args.max_shift_y,
        min_shift_x: args.min_shift_x,
        max_shift_x: args.max_shift_x,
        max_drift_x: args.max_drift_x,
        max_drift_y: args.max_drift_y,
        align_scale: args.align_scale,
        snap_x: args.snap_x,
        check_duplicates: args.check_duplicates,
        monotonic_frame_filter: args.monotonic_frame_filter,
        seam_motion_weight: args.seam_motion_weight,
        seam_motion_radius: args.seam_motion_radius,
        seam_motion_threshold: args.seam_motion_threshold,
        seam_motion_mask_dilate: args.seam_motion_mask_dilate,
        seam_motion_hard_penalty: args.seam_motion_hard_penalty,
        seam_edge_weight: args.seam_edge_weight,
    }
}

fn stitch_cli(args: StitchArgs) -> Result<()> {
    let images = load_images(&args.inputs).context("loading input images")?;
    let opts = options_from_args(&args);
    let (stitched, source_map, mut report) =
        stitch_images_with_source_map(&images, &opts).context("stitching images")?;
    stitched
        .save(&args.output)
        .with_context(|| format!("saving {}", args.output.display()))?;
    println!("wrote {}", args.output.display());

    if let Some(path) = &args.source_map {
        source_map
            .to_gray_image()
            .save(path)
            .with_context(|| format!("saving {}", path.display()))?;
        println!("wrote {}", path.display());
    }

    if args.duplicate_overlay {
        let dup = report
            .duplicate_report
            .clone()
            .unwrap_or_else(|| detect_duplicates(&stitched));
        let overlay = draw_duplicate_overlay(&stitched, &dup);
        let overlay_path = overlay_path_for(&args.output);
        overlay
            .save(&overlay_path)
            .with_context(|| format!("saving {}", overlay_path.display()))?;
        println!("wrote {}", overlay_path.display());
        report.duplicate_report = Some(dup);
    }

    if let Some(dup) = &report.duplicate_report {
        if dup.passed {
            println!("DUPLICATE TEST: PASS");
        } else {
            bail!("DUPLICATE TEST: FAIL");
        }
    }

    if let Some(path) = &args.report {
        let json = serde_json::to_string_pretty(&report)?;
        std::fs::write(path, json).with_context(|| format!("writing {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}

fn eval_cli(args: EvalArgs) -> Result<()> {
    let stitched = image::open(&args.stitched)
        .with_context(|| format!("opening {}", args.stitched.display()))?
        .into_rgb8();
    let stitch_report: StitchReport = serde_json::from_slice(
        &std::fs::read(&args.report)
            .with_context(|| format!("reading {}", args.report.display()))?,
    )?;

    let source_map = if let Some(path) = &args.source_map {
        let img = image::open(path)
            .with_context(|| format!("opening {}", path.display()))?
            .into_luma8();
        SourceMap::from_gray_image(&img)
    } else {
        if args.inputs.is_empty() {
            bail!("--inputs are required when --source-map is not provided");
        }
        let inputs = load_images(&args.inputs).context("loading input images")?;
        let (input_w, input_h) = inputs[0].dimensions();
        generate_source_map(
            &stitch_report.normalized_positions,
            input_w,
            input_h,
            stitch_report.canvas_width,
            stitch_report.canvas_height,
        )
    };

    let thresholds = EvalThresholds {
        max_high_risk_boundary_pixels: args.max_high_risk_boundary_pixels,
        max_largest_risky_component_area: args.max_largest_risky_component_area,
        min_mean_gradient: args.min_mean_gradient,
        min_p95_gradient: args.min_p95_gradient,
        ..Default::default()
    };
    let mut report = evaluate_stitch(&stitched, &source_map, thresholds);
    let (stitched_w, stitched_h) = stitched.dimensions();
    if !args.allow_crop
        && (stitched_w < stitch_report.canvas_width || stitched_h < stitch_report.canvas_height)
    {
        report.failures.push(format!(
            "cropped_output {}x{} < reported_canvas {}x{}",
            stitched_w, stitched_h, stitch_report.canvas_width, stitch_report.canvas_height
        ));
    }
    if stitch_report.normalized_positions.len() > 1 && report.source_map_distinct_sources < 2 {
        report.failures.push(format!(
            "source_map_distinct_sources {} < 2 for multi-frame stitch",
            report.source_map_distinct_sources
        ));
    }
    report.passed = report.failures.is_empty();

    if let Some(path) = &args.overlay {
        draw_evaluation_overlay(&stitched, &source_map, &report)
            .save(path)
            .with_context(|| format!("saving {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    if let Some(path) = &args.source_block_overlay {
        draw_source_block_overlay(&stitched, &source_map)
            .save(path)
            .with_context(|| format!("saving {}", path.display()))?;
        println!("wrote {}", path.display());
    }
    if let Some(dir) = &args.component_crops_dir {
        write_component_crops(
            &stitched,
            &source_map,
            &report,
            dir,
            args.component_crop_padding,
            args.max_component_crops,
        )?;
    }

    std::fs::write(&args.output, serde_json::to_string_pretty(&report)?)
        .with_context(|| format!("writing {}", args.output.display()))?;
    println!("wrote {}", args.output.display());

    if report.passed {
        println!("EVAL TEST: PASS");
        Ok(())
    } else {
        bail!("EVAL TEST: FAIL: {}", report.failures.join("; "))
    }
}

fn write_component_crops(
    stitched: &image::RgbImage,
    source_map: &SourceMap,
    report: &stitcher::EvaluationReport,
    dir: &Path,
    padding: u32,
    limit: usize,
) -> Result<()> {
    std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    let source_overlay = draw_source_block_overlay(stitched, source_map);
    for (idx, component) in report.high_risk_components.iter().take(limit).enumerate() {
        let [x, y, w, h] = component.bbox_xywh;
        let x0 = x.saturating_sub(padding);
        let y0 = y.saturating_sub(padding);
        let x1 = (x + w + padding).min(stitched.width());
        let y1 = (y + h + padding).min(stitched.height());
        if x1 <= x0 || y1 <= y0 {
            continue;
        }
        let crop_w = x1 - x0;
        let crop_h = y1 - y0;
        let stem = format!(
            "component_{idx:02}_area_{}_bbox_{}_{}_{}_{}",
            component.area_px, x, y, w, h
        );
        let stitched_crop = image::imageops::crop_imm(stitched, x0, y0, crop_w, crop_h).to_image();
        let source_crop =
            image::imageops::crop_imm(&source_overlay, x0, y0, crop_w, crop_h).to_image();
        let stitched_path = dir.join(format!("{stem}_stitched.png"));
        let source_path = dir.join(format!("{stem}_source_overlay.png"));
        stitched_crop
            .save(&stitched_path)
            .with_context(|| format!("saving {}", stitched_path.display()))?;
        source_crop
            .save(&source_path)
            .with_context(|| format!("saving {}", source_path.display()))?;
        println!("wrote {}", stitched_path.display());
        println!("wrote {}", source_path.display());
    }
    Ok(())
}

async fn serve(args: ServeArgs) -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();
    fs::create_dir_all(&args.output_dir).await?;
    let app = Router::new()
        .route("/", get(index))
        .route("/api/stitch", post(upload_and_stitch))
        .nest_service("/outputs", ServeDir::new(args.output_dir.clone()))
        .layer(DefaultBodyLimit::max(1024 * 1024 * 80))
        .with_state(args.output_dir.clone());

    tracing::info!("serving stitcher GUI at http://{}", args.bind);
    let listener = tokio::net::TcpListener::bind(args.bind).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

async fn index() -> Result<Html<String>, AppError> {
    Ok(Html(IndexTemplate.render()?))
}

async fn upload_and_stitch(
    axum::extract::State(output_dir): axum::extract::State<PathBuf>,
    mut multipart: Multipart,
) -> Result<Json<serde_json::Value>, AppError> {
    let mut images = Vec::new();
    while let Some(field) = multipart.next_field().await? {
        if field.name() != Some("images") {
            continue;
        }
        let bytes = field.bytes().await?;
        let img = image::load_from_memory(&bytes)?.into_rgb8();
        images.push(img);
    }
    if images.len() < 2 {
        return Err(AppError::bad_request("upload at least two images"));
    }

    let opts = StitchOptions {
        check_duplicates: true,
        ..Default::default()
    };
    let (stitched, report) = stitch_images(&images, &opts)?;
    let id = Uuid::new_v4().to_string();
    let png_name = format!("{id}.png");
    let report_name = format!("{id}.json");
    let png_path = output_dir.join(&png_name);
    let report_path = output_dir.join(&report_name);
    stitched.save(&png_path)?;
    fs::write(&report_path, serde_json::to_vec_pretty(&report)?).await?;

    Ok(Json(json!({
        "image_url": format!("/outputs/{png_name}"),
        "report_url": format!("/outputs/{report_name}"),
        "report": report
    })))
}

fn overlay_path_for(output: &Path) -> PathBuf {
    let stem = output
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("stitched");
    let parent = output.parent().unwrap_or_else(|| Path::new("."));
    parent.join(format!("{}_duplicate_overlay.png", stem))
}

#[derive(Debug)]
struct AppError {
    status: StatusCode,
    message: String,
}

impl AppError {
    fn bad_request(message: impl Into<String>) -> Self {
        Self {
            status: StatusCode::BAD_REQUEST,
            message: message.into(),
        }
    }
}

impl From<anyhow::Error> for AppError {
    fn from(err: anyhow::Error) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            message: err.to_string(),
        }
    }
}

impl From<askama::Error> for AppError {
    fn from(err: askama::Error) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            message: err.to_string(),
        }
    }
}

impl From<axum::extract::multipart::MultipartError> for AppError {
    fn from(err: axum::extract::multipart::MultipartError) -> Self {
        Self {
            status: StatusCode::BAD_REQUEST,
            message: err.to_string(),
        }
    }
}

impl From<image::ImageError> for AppError {
    fn from(err: image::ImageError) -> Self {
        Self {
            status: StatusCode::BAD_REQUEST,
            message: err.to_string(),
        }
    }
}

impl From<std::io::Error> for AppError {
    fn from(err: std::io::Error) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            message: err.to_string(),
        }
    }
}

impl From<serde_json::Error> for AppError {
    fn from(err: serde_json::Error) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            message: err.to_string(),
        }
    }
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let body = Json(json!({ "error": self.message }));
        (self.status, body).into_response()
    }
}

#[allow(dead_code)]
fn image_response_png(img: &image::RgbImage) -> Result<Response> {
    let mut bytes = Vec::new();
    img.write_to(&mut Cursor::new(&mut bytes), ImageFormat::Png)?;
    let mut headers = HeaderMap::new();
    headers.insert(header::CONTENT_TYPE, HeaderValue::from_static("image/png"));
    Ok((headers, bytes).into_response())
}
